theme: jekyll-theme-minimal
title: SamplingStrata
description: R package for Optimal Stratification of Sampling Frames for Multipurpose Sampling Surveys
url: https://github.com/barcaroli/SamplingStrata
author: Giulio Barcaroli
plugins:
  - jekyll-seo-tag
